#????????? ???????
server.port=8080

#Spring
spring.application.name=hplc-column-management

#Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

#???????????
logging.level.root=WARN
logging.level.io.github.deanmave=DEBUG