#Server
server.port=8080

#Spring
spring.application.name=hplc-column-management

#Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

#Logging
logging.level.root=WARN
logging.level.io.github.deanmave=DEBUG

#JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

#Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/hplc_db
spring.datasource.username=hplc_user
spring.datasource.password=hplc1234