#Server
server.port=8080

#Spring
spring.application.name=hplc-column-management

#Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

#Logging
logging.level.root=WARN
logging.level.io.github.deanmave=DEBUG

#JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres